# User configuration options
[user]
home_lat = 32.800016
home_lon = -117.052769
home_radius = 100

# App configuration options
[app]
app_width = 1024
app_height = 600
get_new_flight_interval = 12
max_airline_name_length = 30
airline_logo_url = https://www.flightaware.com/images/airline_logos/180px/
airline_logo_url_ext = .png
ui_file_name = flight-tracker.ui
airlines_only = True
has_position = True
on_ground = False
has_origin_destination = True

[get_new_flight]
delay = 3

[get_flights]
delay = 10

[get_dark_mode]
delay = 5
